# mpd/mpd.conf (Universal en Git)
auto_update    "yes"
restore_paused "yes"
#crossfade      "4"

# Archivos de gestión interna
playlist_directory "~/.config/mpd/playlists"
db_file            "~/.config/mpd/database"
pid_file           "~/.config/mpd/pid"
state_file         "~/.config/mpd/state"

# Cargar la configuración de hardware específica de cada dispositivo
include "mpd_local.conf"
